# Generated by Django 4.0 on 2021-12-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, height_field='height', help_text='Укажите фаил картинки', null=True, upload_to='%Y/%m/%d', verbose_name='Картинка', width_field='width')),
                ('url', models.CharField(blank=True, help_text='Укажите ссылку на внешнюю картинку', max_length=255, null=True, verbose_name='Внешняя картинка')),
                ('name', models.CharField(blank=True, help_text='Укажите имя картинки', max_length=255, verbose_name='Имя картинки')),
                ('width', models.PositiveIntegerField(help_text='Ширина Картинки', null=True, verbose_name='Ширина Картинки')),
                ('height', models.PositiveIntegerField(help_text='Высота Картинки', null=True, verbose_name='Высота Картинки')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Укажите дату публикации картинки', verbose_name='Дата публикации картинки')),
                ('parent_picture', models.ForeignKey(blank=True, help_text='Укажите родителя картинки', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ('id',),
            },
        ),
    ]
