# Generated by Django 4.0 on 2022-01-02 09:25

import api.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', api.fields.HeifmgurField(blank=True, height_field='height', help_text='Specify image file', null=True, upload_to='%Y/%m/%d', verbose_name='Image', width_field='width')),
                ('url', models.CharField(blank=True, help_text='Specify picture url', max_length=255, null=True, verbose_name='External picture')),
                ('name', models.CharField(blank=True, help_text='Specify name of the picture', max_length=255, verbose_name='Picture name')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='Picture width')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='Picture height')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of publication')),
                ('parent_picture', models.ForeignKey(blank=True, help_text='Specify parent picture', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('id',),
            },
        ),
    ]
